modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory

authors="${author}" #optional

license="MIT License" #mandatory

[[mods]] #mandatory

modId="mycoordinatesmods" #mandatory

version="0.8" #mandatory

displayName="My Coordinates Mod" #mandatory

description='''${desc}'''

[[dependencies.mycoordinatesmods]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[32,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.mycoordinatesmods]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1]"
ordering="NONE"
side="BOTH"
