modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory

authors="quentin452" #optional

license=" LGPL-3.0-only" #mandatory

[[mods]] #mandatory

modId="mycoordinatesmods" #mandatory

version="0.8" #mandatory

displayName="My Coordinates Mod" #mandatory

description=''''''

[[dependencies.mycoordinatesmods]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[32,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.mycoordinatesmods]]
modId="minecraft"
mandatory=true
versionRange="[1.20.6]"
ordering="NONE"
side="BOTH"
[mixin]
config="mycoordinatesmods.mixins.json"
